<ul><li rel="drive" id="dept_1"><a href="#">xxx医院</a>
<ul><li rel="folder" id="dept_66"><a href="#">院部</a>
<ul><li rel="default" id="dept_83"><a href="#">院长</a>
</li><li rel="default" id="dept_84"><a href="#">政委</a>
</li><li rel="default" id="dept_85"><a href="#">副院长</a>
</li><li rel="default" id="dept_86"><a href="#">秘书</a>
</li></ul></li><li rel="folder" id="dept_67"><a href="#">医务处</a>
<ul><li rel="default" id="dept_87"><a href="#">主任</a>
</li><li rel="default" id="dept_88"><a href="#">副主任</a>
</li><li rel="folder" id="dept_89"><a href="#">训练队</a>
<ul><li rel="default" id="dept_90"><a href="#">队长</a>
</li><li rel="default" id="dept_91"><a href="#">助理员</a>
</li></ul></li></ul></li><li rel="folder" id="dept_68"><a href="#">政治处</a>
<ul><li rel="default" id="dept_92"><a href="#">主任</a>
</li><li rel="default" id="dept_93"><a href="#">副主任</a>
</li><li rel="default" id="dept_94"><a href="#">干事</a>
</li></ul></li><li rel="folder" id="dept_69"><a href="#">院务处</a>
<ul><li rel="default" id="dept_95"><a href="#">处长</a>
</li><li rel="default" id="dept_96"><a href="#">副处长</a>
</li><li rel="default" id="dept_97"><a href="#">助理员</a>
</li><li rel="folder" id="dept_99"><a href="#">住院处</a>
<ul><li rel="default" id="dept_101"><a href="#">成员</a>
</li></ul></li><li rel="folder" id="dept_100"><a href="#">工作餐厅</a>
<ul><li rel="default" id="dept_102"><a href="#">成员</a>
</li></ul></li></ul></li><li rel="folder" id="dept_70"><a href="#">护理部</a>
<ul><li rel="default" id="dept_103"><a href="#">主任</a>
</li><li rel="default" id="dept_104"><a href="#">总护士长</a>
</li><li rel="default" id="dept_105"><a href="#">助理员</a>
</li></ul></li><li rel="folder" id="dept_71"><a href="#">经济管理部</a>
<ul><li rel="default" id="dept_106"><a href="#">主任</a>
</li><li rel="default" id="dept_107"><a href="#">副主任</a>
</li><li rel="folder" id="dept_108"><a href="#">经济管理科</a>
<ul><li rel="default" id="dept_112"><a href="#">主任</a>
</li><li rel="default" id="dept_113"><a href="#">助理员</a>
</li></ul></li><li rel="folder" id="dept_109"><a href="#">物资供应科</a>
<ul><li rel="default" id="dept_114"><a href="#">主任</a>
</li><li rel="default" id="dept_115"><a href="#">成功</a>
</li></ul></li><li rel="folder" id="dept_110"><a href="#">财务管理科</a>
<ul><li rel="default" id="dept_116"><a href="#">主任</a>
</li><li rel="default" id="dept_117"><a href="#">助理员</a>
</li></ul></li><li rel="folder" id="dept_111"><a href="#">收费挂号处</a>
<ul><li rel="default" id="dept_118"><a href="#">主任</a>
</li><li rel="default" id="dept_119"><a href="#">成员</a>
</li></ul></li></ul></li><li rel="folder" id="dept_72"><a href="#">感染质控科</a>
<ul><li rel="default" id="dept_120"><a href="#">主任</a>
</li><li rel="default" id="dept_121"><a href="#">助理员</a>
</li></ul></li><li rel="folder" id="dept_73"><a href="#">信息科</a>
<ul><li rel="default" id="dept_122"><a href="#">主任</a>
</li><li rel="default" id="dept_123"><a href="#">副主任</a>
</li><li rel="default" id="dept_124"><a href="#">工程师</a>
</li><li rel="default" id="dept_125"><a href="#">技师</a>
</li></ul></li><li rel="folder" id="dept_74"><a href="#">医学工程科</a>
<ul><li rel="default" id="dept_126"><a href="#">主任</a>
</li><li rel="default" id="dept_127"><a href="#">技师</a>
</li><li rel="folder" id="dept_128"><a href="#">供应室</a>
<ul><li rel="default" id="dept_129"><a href="#">护士长</a>
</li><li rel="default" id="dept_130"><a href="#">成员</a>
</li></ul></li></ul></li><li rel="folder" id="dept_75"><a href="#">门诊系统</a>
<ul><li rel="folder" id="dept_131"><a href="#">门诊部</a>
<ul><li rel="default" id="dept_136"><a href="#">主任</a>
</li><li rel="default" id="dept_137"><a href="#">护士长</a>
</li><li rel="default" id="dept_138"><a href="#">成员</a>
</li></ul></li><li rel="folder" id="dept_132"><a href="#">急诊科</a>
<ul><li rel="default" id="dept_139"><a href="#">主任</a>
</li><li rel="default" id="dept_140"><a href="#">护士长</a>
</li><li rel="default" id="dept_141"><a href="#">医生</a>
</li><li rel="default" id="dept_142"><a href="#">护士</a>
</li></ul></li><li rel="folder" id="dept_133"><a href="#">皮肤科</a>
<ul><li rel="default" id="dept_143"><a href="#">主任</a>
</li><li rel="default" id="dept_144"><a href="#">医生</a>
</li><li rel="default" id="dept_145"><a href="#">护士</a>
</li></ul></li><li rel="folder" id="dept_134"><a href="#">保健科</a>
<ul><li rel="default" id="dept_146"><a href="#">主任</a>
</li><li rel="default" id="dept_147"><a href="#">成员</a>
</li></ul></li><li rel="folder" id="dept_135"><a href="#">体检中心</a>
<ul><li rel="default" id="dept_148"><a href="#">主任</a>
</li><li rel="default" id="dept_149"><a href="#">护士长</a>
</li><li rel="default" id="dept_150"><a href="#">成员</a>
</li></ul></li></ul></li><li rel="folder" id="dept_76"><a href="#">内科系统</a>
<ul><li rel="folder" id="dept_151"><a href="#">呼吸科</a>
<ul><li rel="default" id="dept_163"><a href="#">主任</a>
</li><li rel="default" id="dept_164"><a href="#">护士长</a>
</li><li rel="default" id="dept_165"><a href="#">医生</a>
</li><li rel="default" id="dept_166"><a href="#">护士</a>
</li></ul></li><li rel="folder" id="dept_152"><a href="#">消化科</a>
<ul><li rel="default" id="dept_167"><a href="#">主任</a>
</li><li rel="default" id="dept_168"><a href="#">副主任</a>
</li><li rel="default" id="dept_169"><a href="#">护士长</a>
</li><li rel="default" id="dept_170"><a href="#">医生</a>
</li><li rel="default" id="dept_171"><a href="#">护士</a>
</li></ul></li><li rel="folder" id="dept_153"><a href="#">小儿科</a>
<ul><li rel="default" id="dept_172"><a href="#">主任</a>
</li><li rel="default" id="dept_173"><a href="#">护士长</a>
</li><li rel="default" id="dept_174"><a href="#">医生</a>
</li><li rel="default" id="dept_175"><a href="#">护士</a>
</li></ul></li><li rel="folder" id="dept_154"><a href="#">肾内科</a>
<ul><li rel="default" id="dept_176"><a href="#">主任</a>
</li><li rel="default" id="dept_177"><a href="#">护士长</a>
</li><li rel="default" id="dept_178"><a href="#">医生</a>
</li><li rel="default" id="dept_179"><a href="#">护士</a>
</li><li rel="folder" id="dept_180"><a href="#">血液净化</a>
<ul><li rel="default" id="dept_181"><a href="#">主任</a>
</li><li rel="default" id="dept_182"><a href="#">成员</a>
</li></ul></li></ul></li><li rel="folder" id="dept_155"><a href="#">肿瘤科</a>
<ul><li rel="default" id="dept_183"><a href="#">主任</a>
</li><li rel="default" id="dept_184"><a href="#">护士长</a>
</li><li rel="default" id="dept_185"><a href="#">医生</a>
</li><li rel="default" id="dept_186"><a href="#">护士</a>
</li></ul></li><li rel="folder" id="dept_156"><a href="#">血液科</a>
<ul><li rel="default" id="dept_187"><a href="#">主任</a>
</li><li rel="default" id="dept_188"><a href="#">护士长</a>
</li><li rel="default" id="dept_189"><a href="#">医生</a>
</li><li rel="default" id="dept_190"><a href="#">护士</a>
</li></ul></li><li rel="folder" id="dept_191"><a href="#">传染科</a>
<ul><li rel="default" id="dept_192"><a href="#">主任</a>
</li><li rel="default" id="dept_193"><a href="#">护士长</a>
</li><li rel="default" id="dept_194"><a href="#">医生</a>
</li><li rel="default" id="dept_195"><a href="#">护士</a>
</li></ul></li><li rel="folder" id="dept_157"><a href="#">神经内科</a>
<ul><li rel="default" id="dept_196"><a href="#">主任</a>
</li><li rel="default" id="dept_197"><a href="#">护士长</a>
</li><li rel="default" id="dept_198"><a href="#">医生</a>
</li><li rel="default" id="dept_199"><a href="#">护士</a>
</li></ul></li><li rel="folder" id="dept_158"><a href="#">干部病房</a>
<ul><li rel="default" id="dept_200"><a href="#">主任</a>
</li><li rel="default" id="dept_201"><a href="#">副主任</a>
</li><li rel="default" id="dept_202"><a href="#">护士长</a>
</li><li rel="default" id="dept_203"><a href="#">医生</a>
</li><li rel="default" id="dept_204"><a href="#">护士</a>
</li></ul></li><li rel="folder" id="dept_159"><a href="#">内分泌科</a>
<ul><li rel="default" id="dept_205"><a href="#">主任</a>
</li><li rel="default" id="dept_206"><a href="#">护士长</a>
</li><li rel="default" id="dept_207"><a href="#">医生</a>
</li><li rel="default" id="dept_208"><a href="#">护士</a>
</li></ul></li><li rel="folder" id="dept_160"><a href="#">心血管一科</a>
<ul><li rel="default" id="dept_209"><a href="#">主任</a>
</li><li rel="default" id="dept_210"><a href="#">护士长</a>
</li><li rel="default" id="dept_211"><a href="#">医生</a>
</li><li rel="default" id="dept_212"><a href="#">护士</a>
</li></ul></li><li rel="folder" id="dept_161"><a href="#">心血管二科</a>
<ul><li rel="default" id="dept_213"><a href="#">主任</a>
</li><li rel="default" id="dept_214"><a href="#">护士长</a>
</li><li rel="default" id="dept_215"><a href="#">医生</a>
</li><li rel="default" id="dept_216"><a href="#">护士</a>
</li></ul></li><li rel="folder" id="dept_162"><a href="#">中医康复科</a>
<ul><li rel="default" id="dept_217"><a href="#">主任</a>
</li><li rel="default" id="dept_218"><a href="#">副主任</a>
</li><li rel="default" id="dept_219"><a href="#">护士长</a>
</li><li rel="default" id="dept_220"><a href="#">医生</a>
</li><li rel="default" id="dept_221"><a href="#">护士</a>
</li></ul></li></ul></li><li rel="folder" id="dept_77"><a href="#">外科系统</a>
<ul><li rel="folder" id="dept_223"><a href="#">妇科</a>
<ul><li rel="default" id="dept_244"><a href="#">主任</a>
</li><li rel="default" id="dept_245"><a href="#">护士长</a>
</li><li rel="default" id="dept_246"><a href="#">医生</a>
</li><li rel="default" id="dept_247"><a href="#">护士</a>
</li></ul></li><li rel="folder" id="dept_224"><a href="#">产科</a>
<ul><li rel="default" id="dept_248"><a href="#">主任</a>
</li><li rel="default" id="dept_249"><a href="#">护士长</a>
</li><li rel="default" id="dept_250"><a href="#">医生</a>
</li><li rel="default" id="dept_251"><a href="#">护士</a>
</li></ul></li><li rel="folder" id="dept_225"><a href="#">眼科</a>
<ul><li rel="default" id="dept_252"><a href="#">主任</a>
</li><li rel="default" id="dept_253"><a href="#">医生</a>
</li><li rel="default" id="dept_254"><a href="#">护士</a>
</li></ul></li><li rel="folder" id="dept_226"><a href="#">口腔科</a>
<ul><li rel="default" id="dept_255"><a href="#">主任</a>
</li><li rel="default" id="dept_256"><a href="#">副主任</a>
</li><li rel="default" id="dept_257"><a href="#">护士长</a>
</li><li rel="default" id="dept_258"><a href="#">医生</a>
</li><li rel="default" id="dept_259"><a href="#">护士</a>
</li></ul></li><li rel="folder" id="dept_227"><a href="#">麻醉科</a>
<ul><li rel="default" id="dept_260"><a href="#">主任</a>
</li><li rel="default" id="dept_261"><a href="#">副主任</a>
</li><li rel="default" id="dept_262"><a href="#">护士长</a>
</li><li rel="default" id="dept_263"><a href="#">医生</a>
</li><li rel="default" id="dept_264"><a href="#">护士</a>
</li></ul></li><li rel="folder" id="dept_228"><a href="#">泌尿外科</a>
<ul><li rel="default" id="dept_265"><a href="#">主任</a>
</li><li rel="default" id="dept_266"><a href="#">护士长</a>
</li><li rel="default" id="dept_267"><a href="#">医生</a>
</li><li rel="default" id="dept_268"><a href="#">护士</a>
</li></ul></li><li rel="folder" id="dept_229"><a href="#">肝胆外科</a>
<ul><li rel="default" id="dept_269"><a href="#">主任</a>
</li><li rel="default" id="dept_270"><a href="#">护士长</a>
</li><li rel="default" id="dept_271"><a href="#">医生</a>
</li><li rel="default" id="dept_272"><a href="#">护士</a>
</li></ul></li><li rel="folder" id="dept_230"><a href="#">脊柱外科</a>
<ul><li rel="default" id="dept_273"><a href="#">主任</a>
</li><li rel="default" id="dept_274"><a href="#">护士长</a>
</li><li rel="default" id="dept_275"><a href="#">医生</a>
</li><li rel="default" id="dept_276"><a href="#">护士</a>
</li></ul></li><li rel="folder" id="dept_231"><a href="#">心胸外科</a>
<ul><li rel="default" id="dept_277"><a href="#">主任</a>
</li><li rel="default" id="dept_278"><a href="#">护士长</a>
</li><li rel="default" id="dept_279"><a href="#">医生</a>
</li><li rel="default" id="dept_280"><a href="#">护士</a>
</li></ul></li><li rel="folder" id="dept_232"><a href="#">耳鼻喉科</a>
<ul><li rel="default" id="dept_281"><a href="#">主任</a>
</li><li rel="default" id="dept_282"><a href="#">医生</a>
</li><li rel="default" id="dept_283"><a href="#">护士</a>
</li></ul></li><li rel="folder" id="dept_233"><a href="#">重症监护科</a>
<ul><li rel="default" id="dept_284"><a href="#">主任</a>
</li><li rel="default" id="dept_285"><a href="#">护士长</a>
</li><li rel="default" id="dept_286"><a href="#">护士</a>
</li></ul></li><li rel="folder" id="dept_234"><a href="#">普通外一科</a>
<ul><li rel="default" id="dept_287"><a href="#">主任</a>
</li><li rel="default" id="dept_288"><a href="#">护士长</a>
</li><li rel="default" id="dept_289"><a href="#">医生</a>
</li><li rel="default" id="dept_290"><a href="#">护士</a>
</li></ul></li><li rel="folder" id="dept_235"><a href="#">普通外二科</a>
<ul><li rel="default" id="dept_291"><a href="#">主任</a>
</li><li rel="default" id="dept_292"><a href="#">护士长</a>
</li><li rel="default" id="dept_293"><a href="#">医生</a>
</li><li rel="default" id="dept_294"><a href="#">护士</a>
</li></ul></li><li rel="folder" id="dept_236"><a href="#">创伤骨一科</a>
<ul><li rel="default" id="dept_295"><a href="#">主任</a>
</li><li rel="default" id="dept_296"><a href="#">护士长</a>
</li><li rel="default" id="dept_297"><a href="#">医生</a>
</li><li rel="default" id="dept_298"><a href="#">护士</a>
</li></ul></li><li rel="folder" id="dept_237"><a href="#">创伤骨二科</a>
<ul><li rel="default" id="dept_299"><a href="#">主任</a>
</li><li rel="default" id="dept_300"><a href="#">护士长</a>
</li><li rel="default" id="dept_301"><a href="#">医生</a>
</li><li rel="default" id="dept_303"><a href="#">护士</a>
</li></ul></li><li rel="folder" id="dept_238"><a href="#">手足外一科</a>
<ul><li rel="default" id="dept_304"><a href="#">主任</a>
</li><li rel="default" id="dept_305"><a href="#">护士长</a>
</li><li rel="default" id="dept_306"><a href="#">医生</a>
</li><li rel="default" id="dept_307"><a href="#">护士</a>
</li></ul></li><li rel="folder" id="dept_239"><a href="#">手足外二科</a>
<ul><li rel="default" id="dept_308"><a href="#">主任</a>
</li><li rel="default" id="dept_309"><a href="#">护士长</a>
</li><li rel="default" id="dept_310"><a href="#">医生</a>
</li><li rel="default" id="dept_311"><a href="#">护士</a>
</li></ul></li><li rel="folder" id="dept_240"><a href="#">骨关节外科</a>
<ul><li rel="default" id="dept_312"><a href="#">主任</a>
</li><li rel="default" id="dept_313"><a href="#">护士长</a>
</li><li rel="default" id="dept_314"><a href="#">医生</a>
</li><li rel="default" id="dept_315"><a href="#">护士</a>
</li></ul></li><li rel="folder" id="dept_241"><a href="#">神经外一科</a>
<ul><li rel="default" id="dept_316"><a href="#">主任</a>
</li><li rel="default" id="dept_317"><a href="#">护士长</a>
</li><li rel="default" id="dept_318"><a href="#">医生</a>
</li><li rel="default" id="dept_319"><a href="#">护士</a>
</li></ul></li><li rel="folder" id="dept_242"><a href="#">神经外二科</a>
<ul><li rel="default" id="dept_320"><a href="#">主任</a>
</li><li rel="default" id="dept_321"><a href="#">护士长</a>
</li><li rel="default" id="dept_322"><a href="#">医生</a>
</li><li rel="default" id="dept_323"><a href="#">护士</a>
</li></ul></li><li rel="folder" id="dept_243"><a href="#">眼耳鼻喉病区</a>
<ul><li rel="default" id="dept_324"><a href="#">护士长</a>
</li><li rel="default" id="dept_325"><a href="#">护士</a>
</li></ul></li></ul></li><li rel="folder" id="dept_78"><a href="#">辅临科室</a>
<ul><li rel="folder" id="dept_326"><a href="#">超声科</a>
<ul><li rel="default" id="dept_333"><a href="#">主任</a>
</li><li rel="default" id="dept_334"><a href="#">成员</a>
</li></ul></li><li rel="folder" id="dept_327"><a href="#">放射科</a>
<ul><li rel="default" id="dept_335"><a href="#">主任</a>
</li><li rel="default" id="dept_336"><a href="#">副主任</a>
</li><li rel="default" id="dept_337"><a href="#">成员</a>
</li></ul></li><li rel="folder" id="dept_328"><a href="#">检验科</a>
<ul><li rel="default" id="dept_338"><a href="#">主任</a>
</li><li rel="default" id="dept_339"><a href="#">副主任</a>
</li><li rel="default" id="dept_340"><a href="#">技师</a>
</li></ul></li><li rel="folder" id="dept_329"><a href="#">病理科</a>
<ul><li rel="default" id="dept_341"><a href="#">主任</a>
</li><li rel="default" id="dept_342"><a href="#">医生</a>
</li></ul></li><li rel="folder" id="dept_330"><a href="#">药剂科</a>
<ul><li rel="default" id="dept_343"><a href="#">主任</a>
</li><li rel="default" id="dept_344"><a href="#">副主任</a>
</li><li rel="default" id="dept_345"><a href="#">药师</a>
</li><li rel="default" id="dept_346"><a href="#">药士</a>
</li><li rel="default" id="dept_347"><a href="#">护士</a>
</li></ul></li><li rel="folder" id="dept_331"><a href="#">介入中心</a>
<ul><li rel="default" id="dept_348"><a href="#">主任</a>
</li><li rel="default" id="dept_349"><a href="#">成员</a>
</li></ul></li><li rel="folder" id="dept_332"><a href="#">核医学科</a>
<ul><li rel="default" id="dept_350"><a href="#">主任</a>
</li><li rel="default" id="dept_351"><a href="#">成员</a>
</li></ul></li></ul></li><li rel="folder" id="dept_79"><a href="#">其他</a>
<ul><li rel="default" id="dept_352"><a href="#">不在位</a>
</li><li rel="default" id="dept_353"><a href="#">待定</a>
</li></ul></li><li rel="default" id="dept_80"><a href="#">系统管理员</a>
</li></ul></li></ul>